---

- name: deploy mysql
  hosts: mysql
  become: true

  pre_tasks:

    - name: update all packages 
      ansible.builtin.dnf:
        update_cache: yes
      changed_when: false

  roles:
    - mysql
