- name: ensure docker config file exists
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0755

- name: add user to docker
  ansible.builtin.user:
    name: "{{ user_name }}"
    group: docker
    append: yes

- name: config docker daemon.json
  template:
    src: docker_config.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: reload_docker
